name: ${name}
version: ${version}
main: ${group}.haritayukle.haritayukleBukkit
api-version: 1.13
folia-supported: true
softdepend: [dynmap, BlueMap, squaremap, WorldBorder]
load: POSTWORLD
authors: [${author}]
description: ${description}
website: https://www.spigotmc.org/resources/haritayukle.81534/
commands:
  haritayukle:
    description: Generates chunks
    aliases: [cy]
    permission: haritayukle.command
    usage: /haritayukle
permissions:
  haritayukle.command:
    default: op
  haritayukle.command.border:
    default: op
    children: [haritayukle.command]
  haritayukle.command.cancel:
    default: op
    children: [haritayukle.command]
  haritayukle.command.center:
    default: op
    children: [haritayukle.command]
  haritayukle.command.confirm:
    default: op
    children: [haritayukle.command]
  haritayukle.command.continue:
    default: op
    children: [haritayukle.command]
  haritayukle.command.corners:
    default: op
    children: [haritayukle.command]
  haritayukle.command.help:
    default: op
    children: [haritayukle.command]
  haritayukle.command.pattern:
    default: op
    children: [haritayukle.command]
  haritayukle.command.pause:
    default: op
    children: [haritayukle.command]
  haritayukle.command.progress:
    default: op
    children: [haritayukle.command]
  haritayukle.command.quiet:
    default: op
    children: [haritayukle.command]
  haritayukle.command.radius:
    default: op
    children: [haritayukle.command]
  haritayukle.command.reload:
    default: op
    children: [haritayukle.command]
  haritayukle.command.selection:
    default: op
    children: [haritayukle.command]
  haritayukle.command.shape:
    default: op
    children: [haritayukle.command]
  haritayukle.command.silent:
    default: op
    children: [haritayukle.command]
  haritayukle.command.spawn:
    default: op
    children: [haritayukle.command]
  haritayukle.command.start:
    default: op
    children: [haritayukle.command]
  haritayukle.command.trim:
    default: op
    children: [haritayukle.command]
  haritayukle.command.worldborder:
    default: op
    children: [haritayukle.command]
  haritayukle.command.world:
    default: op
    children: [haritayukle.command]
  haritayukle.haritayukle:
    default: false
    children:
      - haritayukle.command
      - haritayukle.command.cancel
      - haritayukle.command.center
      - haritayukle.command.confirm
      - haritayukle.command.continue
      - haritayukle.command.corners
      - haritayukle.command.help
      - haritayukle.command.pattern
      - haritayukle.command.pause
      - haritayukle.command.progress
      - haritayukle.command.quiet
      - haritayukle.command.radius
      - haritayukle.command.reload
      - haritayukle.command.selection
      - haritayukle.command.shape
      - haritayukle.command.silent
      - haritayukle.command.spawn
      - haritayukle.command.start
      - haritayukle.command.worldborder
      - haritayukle.command.world
